services:
  postgres:
    container_name: postgres_go
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
